import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import SvcCards from '../components/SvcCards'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hire Amy!</title>
        <meta name="Hire Amy | Design Services" content="Generated by create next app" />
        <link rel="icon" href="/amyicon.svg" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <SvcCards />
        
      </main>

     
    </div>
  )
}
